"""add missing tables

Revision ID: b116bbedfefc
Revises: 25279d38c60e
Create Date: 2026-02-24 01:18:01.466162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b116bbedfefc'
down_revision: Union[str, Sequence[str], None] = '25279d38c60e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # --- ДОБАВЛЕНО ВРУЧНУЮ: Создание типов ENUM ---
    achievement_category = postgresql.ENUM('SPORT', 'SCIENCE', 'ART', 'VOLUNTEERING', 'OTHER', name='achievementcategory')
    achievement_category.create(op.get_bind(), checkfirst=True)

    achievement_level = postgresql.ENUM('SCHOOL', 'MUNICIPAL', 'REGIONAL', 'FEDERAL', 'INTERNATIONAL', name='achievementlevel')
    achievement_level.create(op.get_bind(), checkfirst=True)
    # ----------------------------------------------

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_table('season_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('season_name', sa.String(length=100), nullable=False),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_season_results_id'), 'season_results', ['id'], unique=False)
    op.add_column('achievements', sa.Column('category', sa.Enum('SPORT', 'SCIENCE', 'ART', 'VOLUNTEERING', 'OTHER', name='achievementcategory'), nullable=False))
    op.add_column('achievements', sa.Column('level', sa.Enum('SCHOOL', 'MUNICIPAL', 'REGIONAL', 'FEDERAL', 'INTERNATIONAL', name='achievementlevel'), nullable=False))
    op.add_column('achievements', sa.Column('points', sa.Integer(), nullable=True))
    op.add_column('achievements', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('achievements', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('achievements', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_index(op.f('ix_achievements_id'), 'achievements', ['id'], unique=False)
    op.drop_column('achievements', 'preview_path')
    op.add_column('user_tokens', sa.Column('token_type', sa.String(), nullable=False))
    op.alter_column('user_tokens', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('user_tokens', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_constraint(op.f('user_tokens_token_key'), 'user_tokens', type_='unique')
    op.create_index(op.f('ix_user_tokens_token'), 'user_tokens', ['token'], unique=False)
    op.drop_column('user_tokens', 'type')
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('SUPER_ADMIN', 'ADMIN', 'USER', 'GUEST', 'STUDENT', 'MODERATOR', name='user_role'),
               nullable=True)
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('SUPER_ADMIN', 'ADMIN', 'USER', 'GUEST', 'STUDENT', 'MODERATOR', name='user_role'),
               nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('user_tokens', sa.Column('type', postgresql.ENUM('RESET_PASSWORD', 'EMAIL_VERIFICATION', name='user_token_type'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_user_tokens_token'), table_name='user_tokens')
    op.create_unique_constraint(op.f('user_tokens_token_key'), 'user_tokens', ['token'], postgresql_nulls_not_distinct=False)
    op.alter_column('user_tokens', 'expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('user_tokens', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('user_tokens', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('user_tokens', 'token_type')
    op.add_column('achievements', sa.Column('preview_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_achievements_id'), table_name='achievements')
    op.alter_column('achievements', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('achievements', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('achievements', 'updated_at')
    op.drop_column('achievements', 'points')
    op.drop_column('achievements', 'level')
    op.drop_column('achievements', 'category')
    op.drop_index(op.f('ix_season_results_id'), table_name='season_results')
    op.drop_table('season_results')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###

    # --- ДОБАВЛЕНО ВРУЧНУЮ: Удаление типов ENUM ---
    achievement_category = postgresql.ENUM('SPORT', 'SCIENCE', 'ART', 'VOLUNTEERING', 'OTHER', name='achievementcategory')
    achievement_category.drop(op.get_bind(), checkfirst=True)

    achievement_level = postgresql.ENUM('SCHOOL', 'MUNICIPAL', 'REGIONAL', 'FEDERAL', 'INTERNATIONAL', name='achievementlevel')
    achievement_level.drop(op.get_bind(), checkfirst=True)
    # ----------------------------------------------